# -*- coding: utf-8 -*-
"""Day1 Data Acquisition.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CpQ3NBw6cUp9ApGegkmK9zTlB8cHRCE
"""

import requests
import pandas as pd

BASE_URL = "https://genexahealth.onrender.com/api/v1"
USERNAME = "clinician"
PASSWORD = "clinical123"

class GenexaClient:
    def __init__(self, base_url=BASE_URL, username=USERNAME, password=PASSWORD):
        self.base_url = base_url
        self.token = self._authenticate(username, password)
        self.headers = {"Authorization": f"Bearer {self.token}"}

    def _authenticate(self, username, password):
        """Login and retrieve JWT token."""
        url = f"{self.base_url}/token"
        data = {"username": username, "password": password}
        resp = requests.post(url, data=data)
        resp.raise_for_status()
        return resp.json()["access_token"]

    def get_patient_ids(self):
        url = f"{self.base_url.replace('/api/v1','')}/api/v1/patient_ids"
        resp = requests.get(url, headers=self.headers)
        resp.raise_for_status()
        return resp.json()["patient_ids"]

    def get_table(self, table: str, limit=100, offset=0) -> pd.DataFrame:
        """Fetch table data as pandas DataFrame."""
        url = f"{self.base_url}/{table}/?limit={limit}&offset={offset}"
        resp = requests.get(url, headers=self.headers)
        resp.raise_for_status()
        return pd.DataFrame(resp.json())

    def get_record(self, table: str, patient_id: str) -> dict:
        """Fetch a single record by Patient_ID."""
        url = f"{self.base_url}/{table}/{patient_id}"
        resp = requests.get(url, headers=self.headers)
        if resp.status_code == 404:
            return None
        resp.raise_for_status()
        return resp.json()

    def get_full_table(self, table: str, batch_size=500) -> pd.DataFrame:
        all_data = []
        offset = 0

        while True:
            url = f"{self.base_url}/{table}/?limit={batch_size}&offset={offset}"
            resp = requests.get(url, headers=self.headers)
            resp.raise_for_status()
            batch = resp.json()

            if not batch:
                break

            all_data.extend(batch)
            offset += batch_size

        return pd.DataFrame(all_data)

if __name__ == "__main__":
    client = GenexaClient()

    clinical_df = client.get_full_table("clinical")
    genomics_df = client.get_full_table("genomics")
    lifestyle_df = client.get_full_table("lifestyle")
    outcomes_df = client.get_full_table("outcomes")

    # Print shapes
    print("Clinical shape:", clinical_df.shape)
    print("Genomics shape:", genomics_df.shape)
    print("Lifestyle shape:", lifestyle_df.shape)
    print("Outcomes shape:", outcomes_df.shape)

    # Save to CSV
    clinical_df.to_csv("clinical.csv", index=False)
    genomics_df.to_csv("genomics.csv", index=False)
    lifestyle_df.to_csv("lifestyle.csv", index=False)
    outcomes_df.to_csv("outcomes.csv", index=False)

    print("\nCSV files saved: clinical.csv, genomics.csv, lifestyle.csv, outcomes.csv")

# data consolidation

def merge_patient_data(clinical_df, genomics_df, lifestyle_df, outcomes_df):
    """
    Merge all four tables into a single patient-level DataFrame.
    clinical_df is used as the anchor, joined on Patient_ID.
    """

    # Ensure Patient_ID is string in all
    for df in (clinical_df, genomics_df, lifestyle_df, outcomes_df):
        if "Patient_ID" in df.columns:
            df["Patient_ID"] = df["Patient_ID"].astype(str)

    outcomes_df = outcomes_df.rename(
        columns={"Time_in_Therapeutic_Range_Pct": "TTR_pct"}
    )

    # Merge: Clinical (anchor) ← Genomics ← Lifestyle ← Outcomes
    merged = clinical_df.merge(genomics_df, on="Patient_ID", how="left", suffixes=("", "_gen"))
    merged = merged.merge(lifestyle_df, on="Patient_ID", how="left", suffixes=("", "_life"))
    merged = merged.merge(outcomes_df, on="Patient_ID", how="left", suffixes=("", "_out"))

    # ---- Example feature engineering ----
    if "CYP2C9" in merged.columns:
        merged["CYP2C9_pcyp3"] = merged["CYP2C9"].isin(["*3/*3", "*2/*3", "*1/*3"]).astype(int)

    if "VKORC1" in merged.columns:
        merged["VKORC1_AA"] = (merged["VKORC1"] == "A/A").astype(int)

    if "Amiodarone" in merged.columns:
        merged["On_Amiodarone"] = merged["Amiodarone"].fillna(0).astype(int)

    if "Alcohol_Intake" in merged.columns:
        alcohol_map = {"None": 0, "Light": 1, "Moderate": 2, "Heavy": 3, None: 0}
        merged["Alcohol_Score"] = merged["Alcohol_Intake"].map(alcohol_map).fillna(0).astype(int)

    if "Diet_VitK_Intake" in merged.columns:
        vitk_map = {"Low": 0, "Medium": 1, "High": 2}
        merged["VitK_Score"] = merged["Diet_VitK_Intake"].map(vitk_map).fillna(1).astype(int)

    for col in ["Weight_kg", "Age"]:
        if col in merged.columns:
            merged[col] = pd.to_numeric(merged[col], errors="coerce")
            merged[col].fillna(merged[col].median(), inplace=True)

    for col in ["Final_Stable_Dose_mg", "INR_Stabilization_Days", "TTR_pct"]:
        if col in merged.columns:
            merged[col] = pd.to_numeric(merged[col], errors="coerce")

    return merged


if __name__ == "__main__":
    merged_df = merge_patient_data(clinical_df, genomics_df, lifestyle_df, outcomes_df)
    print("Merged dataset shape:", merged_df.shape)
    print(merged_df.head())

    # Save for later use
    merged_df.to_csv("combined_clean.csv", index=False)
    print("Merged data saved to combined_clean")

import shutil
from google.colab import files
import os

# 1. Create a folder to save everything
folder_name = "day1"
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

# 2. Copy all files and directories from the current working directory into this folder
for item in os.listdir():
    if item != folder_name:  # Avoid copying the folder into itself
        shutil.copytree(item, os.path.join(folder_name, item), dirs_exist_ok=True) if os.path.isdir(item) else shutil.copy2(item, folder_name)

# 3. Zip the folder
shutil.make_archive(folder_name, 'zip', folder_name)

# 4. Download the zip
files.download(folder_name + ".zip")

