# -*- coding: utf-8 -*-
"""DAY 5: MODEL PROTOTYPE.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4sqTUO3zEZs0bS4iWQ6JArOLxoMmEHH

# DAY 5: MODEL EXPLAINABILITY & PROTOTYPE DEPLOYMENT

###  Install required packages
"""

import pandas as pd, numpy as np, matplotlib.pyplot as plt, joblib, warnings
warnings.filterwarnings('ignore')

"""### Load model and preprocessor"""

import pandas as pd, numpy as np, matplotlib.pyplot as plt, joblib, warnings
warnings.filterwarnings('ignore')

# Load final trained model
model = joblib.load('final_warfarin_model_xgboost.pkl')

# Load processed datasets (numeric, correct schema)
X_train = pd.read_csv('X_train_processed.csv')
X_test  = pd.read_csv('X_test_processed.csv')
y_test  = pd.read_csv('y_test.csv').squeeze()

# Load feature names safely (CSV has no header, just one column)
feature_df = pd.read_csv('feature_names.csv', header=None)
feature_names = feature_df.iloc[:, 0].tolist()

print(f"Model: {type(model).__name__}")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")
print(f"Number of features: {len(feature_names)}")
print("First 5 feature names:", feature_names[:5])

"""### GLOBAL SHAP EXPLANATION"""

import shap # For tree-based models
explainer = shap.TreeExplainer(model)
# Compute Global Predictors of Warfarin Dose
shap_values = explainer.shap_values(X_train.sample(100, random_state=42))
importance_vals = np.abs(shap_values).mean(axis=0)

# Create sorted table
importance_table = pd.DataFrame({
    "Feature": X_train.columns,
    "Mean |SHAP value|": importance_vals
}).sort_values("Mean |SHAP value|", ascending=False)

# --- BAR PLOT ---
plt.figure(figsize=(8,6))
plt.barh(importance_table["Feature"].head(10)[::-1],
         importance_table["Mean |SHAP value|"].head(10)[::-1])
plt.xlabel("Mean |SHAP value| (impact on dose prediction)")
plt.title("Top Global Predictors of Warfarin Dose")
plt.show()

# --- TABLE ---
print("\nTop Global Predictors of Warfarin Dose (SHAP Importance):")
print(importance_table.head(10))

# Initialize SHAP explainer for tree-based model
explainer = shap.TreeExplainer(model, feature_perturbation="tree_path_dependent")

# Take a sample of the training data (for faster computation)
X_sample = X_train.sample(min(500, len(X_train)), random_state=42)

# Compute SHAP values
shap_values = explainer.shap_values(X_sample)

# Create a single, comprehensive SHAP summary plot
plt.figure(figsize=(12, 8))
shap.summary_plot(
    shap_values,
    X_sample,
    feature_names=feature_names,
    plot_type="dot",  # Shows both magnitude and direction
    show=False
)
plt.title("Global Feature Importance for Warfarin Dose Prediction", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""- The SHAP importance results show that warfarin dose prediction in the model is driven primarily by genetics, with VKORC1 sensitivity and CYP2C9 activity being the strongest global predictors, reflecting their well‑established role in determining dose requirements; ethnicity, particularly Asian background, also has a notable effect, while age and weight contribute moderately in line with clinical expectations that older or lighter patients need lower doses and heavier patients need higher doses, and factors like height or “other” ethnicity categories have minimal impact, confirming the model is capturing clinically sensible patterns.

### LOCAL PATIENT EXPLANATIONS
"""

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
def explain_patient_top3(patient_idx):
    """Generate SHAP explanation for individual patient (top 3 features only)"""
    # Select one patient row
    patient_data = X_test.iloc[patient_idx:patient_idx+1]
    prediction = model.predict(patient_data)[0]

    # Compute SHAP values
    patient_shap = explainer.shap_values(patient_data)[0]

    # Get absolute importance per feature
    importance_vals = np.abs(patient_shap)
    top_idx = np.argsort(importance_vals)[-3:]  # indices of top 3 features

    # Prepare data for plotting
    top_features = X_test.columns[top_idx]
    top_values = patient_shap[top_idx]

    # Bar plot of top 3 features
    plt.figure(figsize=(6,4))
    plt.barh(top_features, top_values, color=["steelblue" if v>0 else "salmon" for v in top_values])
    plt.xlabel("SHAP value (impact on dose prediction)")
    plt.title(f"Patient {patient_idx} – Top 3 Feature Contributions")
    plt.show()

    return prediction

# Collect results for selected patients
results = []
for idx in [10, 50, 100]:
    dose = explain_patient_top3(idx)
    actual = y_test.iloc[idx]
    results.append({"Patient": idx, "Actual Dose": actual, "Predicted Dose": dose})
    print(f"Patient {idx}: Predicted dose = {dose:.2f} mg (Actual = {actual:.2f} mg)")

# Build results table
results_df = pd.DataFrame(results)
print("\nActual vs Predicted Warfarin Dose for Selected Patients:")
print(results_df)

# --- MODEL PERFORMANCE STATS ---
# Get predictions for the full test set
y_pred = model.predict(X_test)

# Compute evaluation metrics
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5
r2 = r2_score(y_test, y_pred)

print(f"\nModel Performance on Test Set:")
print(f"RMSE: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

"""**Clinical context:** Warfarin dosing is challenging with typical clinical error rates of 30-40%. These predictions are within ±1 mg, which is excellent - comparable to expert clinician performance. The model appears to capture key genetic and clinical determinants correctly.

**Overall Model Performance:**
- RMSE = 0.64 mg: On average, predictions are off by less than 1 mg - clinically reasonable for warfarin dosing

- R² = 0.84: Model explains 84% of dose variability excellent predictive power

CLINICAL VALIDATION CHECKS
"""

def clinical_validation():
    """Validate model aligns with clinical expectations"""
    results = []

    # Check genetic feature impact
    genetic_features = [f for f in feature_names if 'CYP2C9' in f or 'VKORC1' in f]
    for feat in genetic_features[:3]:
        corr = np.corrcoef(X_test[feat], y_test)[0,1]
        results.append((feat, corr))
        print(f"{feat} correlation with dose: {corr:.3f}")

        # Scatter plot of feature vs dose
        plt.figure(figsize=(6,4))
        plt.scatter(X_test[feat], y_test, alpha=0.5)
        plt.xlabel(feat)
        plt.ylabel("Actual Dose (mg)")
        plt.title(f"{feat} vs Warfarin Dose (corr={corr:.3f})")
        plt.show()

    # Check demographic patterns
    if 'Age' in X_test.columns:
        age_corr = np.corrcoef(X_test['Age'], y_test)[0,1]
        print(f"Age correlation: {age_corr:.3f} (expected negative)")

        # Scatter plot for Age
        plt.figure(figsize=(6,4))
        plt.scatter(X_test['Age'], y_test, alpha=0.5, color="orange")
        plt.xlabel("Age")
        plt.ylabel("Actual Dose (mg)")
        plt.title(f"Age vs Warfarin Dose (corr={age_corr:.3f})")
        plt.show()

    # Save validation report to file
    with open('clinical_validation.txt', 'w') as f:
        f.write("CLINICAL VALIDATION RESULTS\n")
        f.write("="*40 + "\n")
        for feat, corr in results:
            f.write(f"{feat}: {corr:.3f}\n")
        if 'Age' in X_test.columns:
            f.write(f"Age: {age_corr:.3f}\n")

    return results

# Run validation
validation = clinical_validation()
print("\nSummary of validation results:", validation)

"""**Clinical Sound**
- Positive correlation for CYP2C9 activity → higher enzyme activity → higher dose needed.
- Negative correlation for VKORC1 sensitivity → more sensitive genotype → lower dose needed.
- Negative correlation for Age → older patients → lower dose needed.

### GRADIO PROTOTYPE (INTERACTIVE)
"""

import joblib
import warnings
import gradio as gr

warnings.filterwarnings('ignore')

# Load trained model (expects manually one-hot/encoded columns)
model = joblib.load("final_warfarin_model_xgboost.pkl")

# CYP2C9 Activity scores
CYP2C9_ACTIVITY = {"Normal": 2.0, "Intermediate": 1.0, "Poor": 0.5}

# VKORC1 Sensitivity scores
VKORC1_SENS = {"GG": 0.0, "AG": 1.0, "AA": 2.0}

# CYP4F2 Score
# CC = 0.0, CT = 0.5, TT = 2.0 is typical in literature
CYP4F2_SCORE = {"CC": 0.0, "CT": 0.5, "TT": 2.0}

# Genetic Burden (continuous, already in training data)
# Let's calculate it properly: normalized sum of genetic scores
def calculate_genetic_burden(cyp2c9, vkorc1, cyp4f2):
    """Calculate genetic burden as normalized sum of genetic scores (0-2 scale)"""
    cyp2c9_score = CYP2C9_ACTIVITY.get(cyp2c9, 2.0)  # 0.5-2.0
    vkorc1_score = VKORC1_SENS.get(vkorc1, 0.0)      # 0-2.0
    cyp4f2_score = CYP4F2_SCORE.get(cyp4f2, 0.0)     # 0-2.0

    # Normalize to 0-2 scale (since training used continuous 0-2)
    # Each component contributes proportionally to its max possible
    burden = (
        (2.0 - cyp2c9_score) * 0.4 +  # CYP2C9: lower activity = higher burden
        vkorc1_score * 0.4 +          # VKORC1: higher sensitivity = higher burden
        cyp4f2_score * 0.2            # CYP4F2: higher score = higher burden
    )

    return round(burden, 2)

# Ethnicity - EXACT one-hot from the training data
ETHNICITY_OHE = {
    "Asian": {
        'Ethnicity_Asian': 1,
        'Ethnicity_Caucasian': 0,
        'Ethnicity_Hispanic': 0,
        'Ethnicity_Other': 0
    },
    "Caucasian": {
        'Ethnicity_Asian': 0,
        'Ethnicity_Caucasian': 1,
        'Ethnicity_Hispanic': 0,
        'Ethnicity_Other': 0
    },
    "Hispanic": {
        'Ethnicity_Asian': 0,
        'Ethnicity_Caucasian': 0,
        'Ethnicity_Hispanic': 1,
        'Ethnicity_Other': 0
    },
    "Other": {
        'Ethnicity_Asian': 0,
        'Ethnicity_Caucasian': 0,
        'Ethnicity_Hispanic': 0,
        'Ethnicity_Other': 1
    }
}

# Alcohol Intake - EXACT from the training data categories
ALCOHOL_OHE = {
    "Heavy": {
        'Alcohol_Intake_Light': 0,
        'Alcohol_Intake_Moderate': 0,
        'Alcohol_Intake_Unknown': 0
    },
    "Light": {
        'Alcohol_Intake_Light': 1,
        'Alcohol_Intake_Moderate': 0,
        'Alcohol_Intake_Unknown': 0
    },
    "Moderate": {
        'Alcohol_Intake_Light': 0,
        'Alcohol_Intake_Moderate': 1,
        'Alcohol_Intake_Unknown': 0
    },
    "Unknown": {
        'Alcohol_Intake_Light': 0,
        'Alcohol_Intake_Moderate': 0,
        'Alcohol_Intake_Unknown': 1
    }
}

# Smoking Status - EXACT from the training data categories
SMOKING_OHE = {
    "Former Smoker": {
        'Smoking_Status_Non-smoker': 1,
        'Smoking_Status_Smoker': 0
    },
    "Non-smoker": {
        'Smoking_Status_Non-smoker': 1,
        'Smoking_Status_Smoker': 0
    },
    "Smoker": {
        'Smoking_Status_Non-smoker': 0,
        'Smoking_Status_Smoker': 1
    }
}

# Diet Vitamin K Intake - EXACT from the training data categories
DIET_OHE = {
    "High": {
        'Diet_VitK_Intake_Low': 0,
        'Diet_VitK_Intake_Medium': 0
    },
    "Low": {
        'Diet_VitK_Intake_Low': 1,
        'Diet_VitK_Intake_Medium': 0
    },
    "Medium": {
        'Diet_VitK_Intake_Low': 0,
        'Diet_VitK_Intake_Medium': 1
    },
    "Unknown": {
        'Diet_VitK_Intake_Low': 0,
        'Diet_VitK_Intake_Medium': 0  # Treat as High (reference)
    }
}

# Model-required column order - EXACT from the training data (19 features)
COLUMNS_ORDER = [
    'Age', 'Weight_kg', 'Height_cm', 'CYP2C9_Activity', 'VKORC1_Sensitivity',
    'CYP4F2_Score', 'Genetic_Burden', 'Sex_M',
    'Ethnicity_Asian', 'Ethnicity_Caucasian', 'Ethnicity_Hispanic', 'Ethnicity_Other',
    'Alcohol_Intake_Light', 'Alcohol_Intake_Moderate', 'Alcohol_Intake_Unknown',
    'Smoking_Status_Non-smoker', 'Smoking_Status_Smoker',
    'Diet_VitK_Intake_Low', 'Diet_VitK_Intake_Medium'
]

# ---------- IMPROVED PREDICTION FUNCTION ----------

def predict_warfarin(age, weight, height_cm, cyp2c9, vkorc1, cyp4f2, ethnicity,
                     sex, alcohol, smoking, diet_vitk,
                     amiodarone=False, antibiotics=False, statins=False, aspirin=False):
    """
    Pharmacogenetic warfarin dose prediction using EXACT training data schema.
    Genetic burden calculated based on established literature weights.
    """

    try:
        # --- Use sensible defaults based on population averages ---
        if cyp2c9 is None: cyp2c9 = "Normal"        # Most common
        if vkorc1 is None: vkorc1 = "AG"            # Most common globally
        if cyp4f2 is None: cyp4f2 = "CC"            # Most common
        if ethnicity is None: ethnicity = "Caucasian"  # Default
        if sex is None: sex = "M"
        if alcohol is None: alcohol = "Unknown"      # Most conservative
        if smoking is None: smoking = "Non-smoker"   # Most common
        if diet_vitk is None: diet_vitk = "Medium"   # Typical

        # Default weight/height based on global averages
        if weight is None: weight = 70.0 if sex == "M" else 65.0
        if height_cm is None: height_cm = 175.0 if sex == "M" else 162.0

        # Convert inputs
        age = int(age)
        weight = float(weight)
        height_cm = float(height_cm)

        # Calculate derived metrics
        height_m = height_cm / 100.0
        bmi = weight / (height_m ** 2) if height_m > 0 else 0

        # Calculate genetic burden using improved method
        genetic_burden = calculate_genetic_burden(cyp2c9, vkorc1, cyp4f2)

        # Get ethnicity mapping - with validation
        ethnicity_map = ETHNICITY_OHE.get(ethnicity, ETHNICITY_OHE["Caucasian"])

        # --- Build EXACT training schema row ---
        patient_data = {
            # Continuous features
            "Age": age,
            "Weight_kg": weight,
            "Height_cm": height_cm,
            "CYP2C9_Activity": CYP2C9_ACTIVITY[cyp2c9],
            "VKORC1_Sensitivity": VKORC1_SENS[vkorc1],
            "CYP4F2_Score": CYP4F2_SCORE[cyp4f2],
            "Genetic_Burden": genetic_burden,

            # Sex (binary)
            "Sex_M": 1 if sex == "M" else 0,

            # Categorical features (one-hot encoded EXACTLY like training)
            **ethnicity_map,
            **ALCOHOL_OHE[alcohol],
            **SMOKING_OHE[smoking],
            **DIET_OHE[diet_vitk],
        }

        # Ensure all columns exist
        for col in COLUMNS_ORDER:
            patient_data.setdefault(col, 0)

        # Create DataFrame with EXACT column order
        df = pd.DataFrame([patient_data])[COLUMNS_ORDER]

        # Predict dose
        prediction = float(model.predict(df)[0])

        # --- IMPROVED CLINICAL INTERPRETATION ---

        # Genetic summary
        genetic_summary = []
        if cyp2c9 != "Normal":
            effect = "↑ dose req" if cyp2c9 == "Poor" else "↗ dose req"
            genetic_summary.append(f"CYP2C9 {cyp2c9} ({effect})")

        if vkorc1 != "GG":
            effect = "↓ dose req" if vkorc1 == "AA" else "↘ dose req"
            genetic_summary.append(f"VKORC1 {vkorc1} ({effect})")

        if cyp4f2 != "CC":
            effect = "↑ dose req" if cyp4f2 == "TT" else "↗ dose req"
            genetic_summary.append(f"CYP4F2 {cyp4f2} ({effect})")

        # Dose range classification
        if prediction < 2.0:
            dose_class = "VERY LOW"
            dose_icon = "🔴"
            clinical_advice = "Consider alternative anticoagulants or verify genetic testing"
        elif prediction < 3.0:
            dose_class = "LOW"
            dose_icon = "🟡"
            clinical_advice = "Start low, monitor INR closely every 2-3 days initially"
        elif prediction <= 7.0:
            dose_class = "STANDARD"
            dose_icon = "🟢"
            clinical_advice = "Standard initiation protocol, check INR after 48-72h"
        elif prediction <= 10.0:
            dose_class = "HIGH"
            dose_icon = "🟠"
            clinical_advice = "Higher starting dose, confirm patient factors, monitor INR frequently"
        else:
            dose_class = "VERY HIGH"
            dose_icon = "🔴"
            clinical_advice = "Unusual dose - review all inputs, consider drug interactions"

        # Interaction flags
        interactions = []
        if amiodarone:
            interactions.append("• Amiodarone: Potent CYP2C9 inhibitor - 30-50% dose reduction typical")
        if antibiotics:
            interactions.append("• Antibiotics: May alter vitamin K synthesis - monitor INR closely")
        if statins:
            interactions.append("• Statins: Variable interaction - check for specific agent")
        if aspirin:
            interactions.append("• Aspirin: Increases bleeding risk independent of INR - assess indication")

        # Build comprehensive output
        output = f"""
{dose_icon} **WARFARIN DOSE RECOMMENDATION** {dose_icon}
===========================================

**Predicted Maintenance Dose:** **{prediction:.2f} mg/day**
**Classification:** {dose_class} dose range

**Initial Regimen:**
• Start with **{prediction * 0.5:.2f} mg** daily for 2 days
• Check INR after 48-72 hours
• Adjust by 0.5-1 mg based on INR response
• Target INR: 2.0-3.0 (standard) or 2.5-3.5 (mechanical valves)

**Clinical Summary:**
• **Patient:** {age}y {sex}, {ethnicity}, BMI: {bmi:.1f}
• **Genetics:** {', '.join(genetic_summary) if genetic_summary else 'Normal variants'}
• **Genetic Burden Score:** {genetic_burden:.2f}/2.0
• **Lifestyle:** Alcohol: {alcohol}, Smoking: {smoking}, Vitamin K: {diet_vitk}
"""

        if interactions:
            output += f"""
**Drug Interactions ({len(interactions)} present):**
{chr(10).join(interactions)}
"""

        output += f"""
**Clinical Guidance:**
{clinical_advice}
• Genetic factors explain ~40-50% of dose variability
• Ethnicity contributes ~15-20% variability
• Always combine with clinical judgment and INR monitoring

**Model Context:**
• Based on SHAP analysis: VKORC1 > CYP2C9 > Ethnicity > Genetic Burden > Age
• R² = 0.84, RMSE = 0.64 mg (clinically acceptable)
• Trained on n=30,000 simulated patients

---
⚠️ **For research/demonstration purposes only**
Clinical validation required before patient use
"""

        return output

    except Exception as e:
        return f"❌ **Error:** {type(e).__name__}: {str(e)}\n\nPlease check all inputs are valid."

# ---------- IMPROVED GRADIO INTERFACE ----------

interface = gr.Interface(
    fn=predict_warfarin,
    inputs=[
        # Core demographics
        gr.Slider(18, 100, value=65, step=1, label="Age (years)",
                 info="Older patients generally require lower doses"),
        gr.Number(value=70.0, label="Weight (kg)", precision=1,
                 info="Higher weight increases dose requirement"),
        gr.Number(value=170.0, label="Height (cm)", precision=1,
                 info="Used for BMI and body surface area calculation"),

        # Genetic inputs (TOP 3 predictors)
        gr.Radio(["Normal", "Intermediate", "Poor"],
                value="Normal", label="CYP2C9 Phenotype",
                info="Metabolism rate - #2 most important predictor"),
        gr.Radio(["GG", "AG", "AA"],
                value="AG", label="VKORC1 Genotype",
                info="Sensitivity - #1 most important predictor"),
        gr.Radio(["CC", "CT", "TT"],
                value="CC", label="CYP4F2 Genotype",
                info="Vitamin K metabolism - minor contributor"),

        # Demographic factors
        gr.Radio(["Asian", "Caucasian", "Hispanic", "Other"],
                value="Caucasian", label="Ethnicity",
                info="#3 most important predictor - Asian ancestry reduces dose"),
        gr.Radio(["M", "F"],
                value="M", label="Sex",
                info="Male patients often require slightly higher doses"),

        # Lifestyle factors
        gr.Radio(["Unknown", "Light", "Moderate", "Heavy"],
                value="Unknown", label="Alcohol Intake",
                info="Heavy alcohol use may increase dose requirements"),
        gr.Radio(["Non-smoker", "Former Smoker", "Smoker"],
                value="Non-smoker", label="Smoking Status",
                info="Smoking induces CYP enzymes - may increase dose"),
        gr.Radio(["Medium", "Low", "High", "Unknown"],
                value="Medium", label="Dietary Vitamin K",
                info="High vitamin K intake increases dose requirement"),

        # Drug interactions (not in model, for clinical context)
        gr.Checkbox(value=False, label="🚨 Amiodarone",
                   info="Potent CYP2C9 inhibitor - reduces dose by 30-50%"),
        gr.Checkbox(value=False, label="🚨 Recent Antibiotics",
                   info="May alter gut flora and vitamin K synthesis"),
        gr.Checkbox(value=False, label="🚨 Statin Therapy",
                   info="Variable interaction - monitor closely"),
        gr.Checkbox(value=False, label="🚨 Aspirin Use",
                   info="Increases bleeding risk - assess carefully"),
    ],
    outputs=gr.Markdown(label="Clinical Recommendation"),
    title="⚕️ Pharmacogenetic Warfarin Dosing Assistant",
    description="""
    **Evidence-based dosing using top 5 predictors from SHAP analysis:**
    1. VKORC1 Sensitivity  2. CYP2C9 Activity  3. Ethnicity
    4. Genetic Burden  5. Age

    *Uses exact same feature encoding as training data*
    """,
    examples=[
        # Standard middle-aged Caucasian male
        [65, 70.0, 170.0, "Normal", "GG", "CC", "Caucasian", "M",
         "Moderate", "Non-smoker", "Medium", False, False, False, False],

        # High-risk elderly Asian female on amiodarone
        [78, 58.0, 155.0, "Poor", "AA", "TT", "Asian", "F",
         "Unknown", "Non-smoker", "Low", True, False, False, True],

        # Complex Hispanic male case
        [45, 90.0, 185.0, "Intermediate", "AG", "CT", "Hispanic", "M",
         "Heavy", "Smoker", "High", False, True, True, False],

        # Young normal metabolizer
        [32, 82.0, 178.0, "Normal", "GG", "CC", "African American", "M",
         "Light", "Former Smoker", "Medium", False, False, False, False],
    ]
)

# ---------- LAUNCH ----------

if __name__ == "__main__":
    print("🚀 Launching Pharmacogenetic Warfarin Dosing Assistant")
    print("📊 Based on SHAP analysis of 30,000 simulated patients")
    print("🔬 Top 5 predictors: VKORC1 > CYP2C9 > Ethnicity > Genetic Burden > Age")
    print("💡 Access at: http://localhost:7860")
    print("=" * 60)

    # Launch with auto-port selection
    interface.launch(
        share=False,
        server_name="0.0.0.0"
        # Let Gradio find available port automatically
    )

"""This pharmacogenetic warfarin dosing assistant exemplifies precision medicine, built on the exact 19‑feature schema from model training for reliable predictions. It integrates weighted genetic burden scoring (CYP2C9 40%, VKORC1 40%, CYP4F2 20%) to enable risk stratification and categorizes doses into actionable tiers with tailored guidance. Beyond calculation, it contextualizes drug interactions (amiodarone, antibiotics, statins, aspirin) to enhance safety, while genetic explanations clarify how variants alter dose needs. Model performance metrics (R², RMSE, SHAP importance) provide transparency, and disclaimers emphasize its research‑use‑only role, supporting informed clinician–patient discussions on dose optimization."""